### PR TITLE
Update ILTemplate.cs to fix multi-threading issues

### PR DESCRIPTION
**Pull request by ryno1234**
Fixed issue with an assembly attempting to be resolved by multiple threads at the same time.

### CODE REVIEW

**Comment by distantcam** [comment]
This has been merged in manually, and is part of v1.4.0

**Comment by ryno1234** [comment]
So, if I'm understanding the commit correctly, this was resolved in 2015 and just checked in? Just curious.

Thanks!

**Comment by distantcam** [comment]
@ryno1234 It was part of the 2.0 beta, which everyone hated. :/

**Comment by ryno1234** [comment]
Bummer. Thanks for getting this in. We were literally about to build our own version of Costura today and use our own build for our projects. This came at the right time.

Have a great day.

**Pull request closed without merging**
