### PR TITLE
Updated references to 2.0.2

### PR DESCRIPTION
**Pull request by shravan2x**
I've updated the references in the packages.config and nuspec files, but was still unable to get it to compile due to some errors. Let me know if there are other files that need to updated.

### CODE REVIEW

**Comment by SimonCropp** [comment]
>  Let me know if there are other files that need to updated.

We would need it compiling and the tests passing

**Comment by shravan2x** [comment]
My errors appear to be due to bad setup, the vanilla repo did not compile either. I'll spend some more time on this tomorrow.

These are the errors I have:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	Fody		1	Active
Error	CS0006	Metadata file 'C:\Costura-v2-update\Fody\bin\Debug\Costura.Fody.dll' could not be found	Tests	C:\Costura-v2-update\Tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Costura-v2-update\Fody\bin\Debug\Costura.Fody.dll' could not be found	Tests2	C:\Costura-v2-update\Tests2\CSC	1	Active
Error	CS0006	Metadata file 'C:\Costura-v2-update\Fody\bin\Debug\Costura.Fody.dll' could not be found	Tests3	C:\Costura-v2-update\Tests3\CSC	1	Active
Warning		The primary reference "C:\Costura-v2-update\Debug\AssemblyToReferenceMixed.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".	AssemblyToProcess			
Warning		The referenced component 'Mono.Cecil' could not be found.	Fody			
Warning		The referenced component 'Mono.Cecil.Mdb' could not be found.	Fody			
Warning		The referenced component 'Mono.Cecil.Pdb' could not be found.	Fody			
Warning		The referenced component 'Mono.Cecil.Rocks' could not be found.	Fody			
Warning		The referenced component 'System' could not be found.	Fody			
Warning		The referenced component 'System.Core' could not be found.	Fody			
Warning		The referenced component 'System.Xml' could not be found.	Fody			
Warning		The referenced component 'System.Xml.Linq' could not be found.	Fody			
Warning		The referenced project 'AssemblyToReferenceMixed' is targeting a higher framework version (4.6.1) than this project’s current target framework version (4.5). This may lead to build failures if types from assemblies outside this project’s target framework are used by any project in the dependency chain.	AssemblyToProcess			
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.29.3\build\portable-net+sl+win+wpa+wp\Fody.targets.	Fody	C:\Costura-v2-update\Fody\Fody.csproj	122	
Warning		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.29.3\build\portable-net+sl+win+wpa+wp\Fody.targets.	Fody	C:\Costura-v2-update\Fody\Fody.csproj	122	
```

**Comment by CDAGaming** [comment]
OH I GOT IT WORKING @shravan2x

**Comment by CDAGaming** [comment]
Took quite a lot of work, but will make a pr shortly as extension to @shravan2x 's

**Comment by shravan2x** [comment]
Closing since @CDAGaming's PR https://github.com/Fody/Costura/pull/188 is further into solving the issue.

**Pull request closed without merging**
