### PR TITLE
Fixed not respecting DisableFody

### PR DESCRIPTION
**Pull request by AceCoderLaura**
Sorry if my msbuild skills are a little amateur x<

Relates to issue #283

### CODE REVIEW

**Comment by SimonCropp** [comment]
seems to have broken the CI?

**Comment by AceCoderLaura** [comment]
That appears to be an issue with the build environment from the looks of the log.

**Comment by SimonCropp** [comment]
@AceCoderLaura u r correct. the broken CI was my fail. sorry about that.

I have merged this and released it in v3. it is now on nuget, pending an hour or so for nuget to re-index it

**Comment by SimonCropp** [comment]
> Sorry if my msbuild skills are a little amateur

i consider myself in the same category ;)

**Pull request merged**
