### PR TITLE
Add wildcard and regex support.

### PR DESCRIPTION
**Pull request by darvell**
#### Description

Adds basic wildcard support and regex support to Include/Exclude assemblies. 
This was requested in https://github.com/Fody/Costura/issues/239.

#### The solution

Check the string for * at the end, if so, use a .StartsWith() for the comparison, otherwise use Regex.IsMatch() since plain string matching as well as regex patterns will work with this.

### CODE REVIEW

**Comment by SimonCropp** [comment]
@darvell there have been some recent changes in the requirements to raise a PR https://github.com/Fody/Costura/blob/master/.github/pull_request_template.md#you-should-already-be-a-patron

**Comment by darvell** [comment]
I understand that open source projects do tend be thankless things with no money and nothing but time spent and I'm sympathetic to that, hell, i'm more than happy to give money to Fody as a whole and now have. My problem that lies here is that contributions have a pay gate and the ethics of that are bugging me. What incentivizes other developers (i.e me) to help increase the size of the core team if they have to pay the toll?

I know that raising this in a PR is not the greatest place for a discussion but I'm feeling really conflicted towards this and don't see anywhere else to engage.

(I am now a patron.)

**Comment by SimonCropp** [comment]
> My problem that lies here is that contributions have a pay gate

contributors dont have a pay gate. Users of fody have a pay gate: https://github.com/Fody/Fody/blob/master/readme.md#licensingpatron-faqI chose not to enforce that pay gate at nuget usage time due to the complexity and friction involved in that.

> It is expected that all developers using Fody become a Patron on OpenCollective.

> What incentivizes other developers (i.e me) to help increase the size of the core team if they have to pay the toll?

What incentivised them prior to the opencollective change? Fody has been around for 6 years. For that time it has been using the traditional FOSS model. In that time there have been very few people who have helped through significant contributions (eg https://github.com/Fody/Costura/graphs/contributors and https://github.com/Fody/Fody/graphs/contributors) . Unfortunately this was not maintainable moving forward. So it was either find a way to, at least partially, fund the project, or abandon it. https://github.com/Fody/Costura/graphs/contributors

**Comment by SimonCropp** [comment]
as for the PR. do u really need full wildcard support? or would startwith and endswith suffice?  similar to what is done here https://github.com/Fody/Virtuosity/blob/master/Virtuosity.Fody/InclusionChecker.cs

can u also add some unit tests

**Comment by darvell** [comment]
Since I guess there's a simultaneous discussion, if you're not interested in the response feel free to scroll down for the PR related things 😛 

>contributors dont have a pay gate.

I'm contributing and I had to become a patron, I wrote this PR as something that would be useful for many people so one can exclude things like `System.*` when choosing to include all. There just also happened to be an issue requesting that where it was said you'd be happy to accept a PR for it.

>Unfortunately this was not maintainable moving forward. So it was either find a way to, at least partially, fund the project, or abandon it. 

That's understandable. I'm not trying to throw a tantrum about it but I fear that while it may help in the short-term, it might end up pushing away developers from contributing especially in a time where MS is pushing a big "support all the OSS .NET libraries and help make them better" period. I really wish the .NET Foundation initiative were paying out OSS libraries that could  really use it as I (and other developers I know) find everything Fody as a whole provides to be nearly essential. Have you written a WPF application without Fody.NotifyProperty? It's awful.

Not trying to kick up too much of a storm, just want to make sure  that such a deserving project can earn money for all the hard work but without potentially alienating out of the blue developers from sticking to working on Fody and alleviating the stress from you and the others.

**PR Notes**

I think that StartsWith/EndsWith could work better what I've provided in this PR but I would like to correctly update this to allow for partial wildcards, e.g. `*.Resources.*`.  What might be more effective is since it ends up using Regex.Match() at the end if there's no wild, if the string only containers A-z/0-9/*, convert the input to a valid regex string e.g. `Darvell.*` to `Darvell.(.*)`. I might have also noticed a bug by just generically using Regex.Match() since I have not configured it to be okay if it didn't match the whole string as right now if you put in say, `Darvell` you'd get `Darvell.Test` and `Darvell.Hotdog` as well as `DarvellNotActually.Test.Assembly`. I'll fix these up.

**Comment by darvell** [comment]
I've fixed everything up to allow standard entries correctly as well as regex/wildcards at any point of the string. I currently have the integration test working with both a wildcard and a regex statement as a valid test case scenario, not sure if you'd want to also have a unit test on top.

**Comment by SimonCropp** [comment]
My point was wouldnt starts with and ends with be sufficient to meet the requirements without the need for regex. 

For example do u actually have a requirement to do full regex on includes and excludes?

**Comment by SimonCropp** [comment]
And yes add some unit tests

**Comment by SimonCropp** [comment]
> I'm contributing and I had to become a patron

No. You had to pay to be a user. If u don’t actually use this project, then i am happy to triage the PR without u being a patron. But so far in the 6 years of maintaining fody, all (non trivial) prs have come from people who are also using fody

**Comment by SimonCropp** [comment]
thoughts on this https://github.com/Fody/Costura/pull/342#issuecomment-448770562  ?

**Comment by darvell** [comment]
I think not having regex would be fine. My initial target for the PR was just to have very basic wildcard support to be able to ignore System.* related assemblies but after reviewing that issue, felt that it might be desired by some folks. As regex would add further maintenance cost than just the basic `StartsWith()`, I'll update this PR to only allow wildcards.

**Comment by SimonCropp** [comment]
can u also add some doco to the readme

**Comment by darvell** [comment]
Documentation added. A basic note is left for most informing that wildcards can be used at the end of an entry for partial matching, the first instance of mentioning wildcards (in ExcludeAssemblies) has further explanation and examples.

**Comment by SimonCropp** [comment]
thanks. i will deploy this now

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Pull request merged**
