### PR TITLE
Updated Mono.Cecil and Fody weavers to be able to compile again

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
This PR will also contain a fix for the new nested classes being used for dynamic lambda invocations. See https://github.com/Fody/Costura/issues/115 where it all began.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Ready to be reviewed. Note that I did my best to maintain compatibility with the old and new era of anonymous lamda execution, so this should work for all. Sorry it's such a big change :-(

This actually contains 2 changes:

1) Update libs so it actually works with fody 1.29.*
2) Refactor the importer so it can clone nested types

**Comment by GeertvanHorrik** [comment]
btw. the 2nd change is only required when Costura is being compiled by VS 2015 / Roslyn (so it applies to how the ILTemplate is being compiled).

**Comment by kavengagne** [comment]
I'm still having this issue with version 1.3.4 on Visual Studio 2015.

**Comment by GeertvanHorrik** [comment]
@kavengagne I screwed up something in my PR for .NET 4.5. It's fixed in a new PR. Can you let us know what .NET version you are using?

**Comment by kavengagne** [comment]
We are using .NET 4.5, Costura 1.3.5 fixed it

**Comment by GeertvanHorrik** [comment]
Good to hear, I also tested the latest 1.3.5, works on all my projects so far.

**Pull request merged**
