### PR TITLE
fix #738

### LINKED ISSUE #738: Debug: stepping through the imported Costura.Template code does not work
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

Costura

## Version of Library

https://github.com/Fody/Costura/commit/db4231289a9a84e091e5c81409ea3ff39698b8bc

## Steps to Reproduce

- Use `CosturaUtility.Initialize();` in your weaved application
- Put a breakpoint there
- Try to step inside code

## Expected Behavior

It's possible to debug-step through all the ILTemplate code

## Actual Behavior

You can step only to the beginning of the methods, next step will just leave the method.

### PR DESCRIPTION
**Pull request by tom-englert**
### Description of Change ###

Fix handling of debug information/sequence points in AssemblyLoaderImporter.cs

### Issues Resolved ### 

- fixes  #738

### API Changes ###
 
None

### Platforms Affected ### 

- All

### Behavioral Changes ###

None

### Testing Procedure ###

- Put a breakpoint at  the "Integration" test static constructor
- Debug the test
- Step into the `CosturaUtility.Initialize()` method

TODO: not sure how that complies with the outdated version of SourceLink, maybe that needs to be updated?

### PR Checklist ###

- [x] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
> not sure how that complies with the outdated version of SourceLink, maybe that needs to be updated?

@tom-englert I am not sure what you mean here. Could you explain a bit more so I can have a better understanding?

**Review by GeertvanHorrik — APPROVED** [review]
Looks great so far. I did ask a question in the general PR chat.

At first I wasn't sure about the additional reference in integrationtests.csproj, but it's a requirement for the CosturaUtility class.

**Comment by tom-englert** [comment]
@GeertvanHorrik see b9f66fe, looks like this does not break anything.

**Comment by GeertvanHorrik** [comment]
Thanks. That file is part of the repository template as well (so we can patch all repositories at once). I think the reason it does not break is because they are now embedded :)

I'll plan some more testing of pdb files that are not being embedded, I remember I needed it for some stuff that was not working out of the box. For now it's good and will keep it this way.

**Comment by GeertvanHorrik** [comment]
I double checked the code. The build scripts will auto-inject sourcelink (see https://github.com/Fody/Costura/blob/develop/deployment/cake/lib-sourcelink.cake#L61) when doing a release build and all variables are available.

This different package is really used to make sure the pdb files are available at package time (but I don't think it's needed because they are embedded now). So I think we can keep everything as-is and nothing will break during the next time we run repository sync.

**Review by GeertvanHorrik — APPROVED** [review]

**Pull request merged**
