### PR TITLE
Add support for including runtime references under .NET Framework

### LINKED ISSUE #652: Support for IncludeRuntimeReferences in .NET Framework
## Summary

Starting with Costura 5, runtime references are skipped in .NET Framework. It was not the case in Costura 4.1.0. This is needed to properly embed `Microsoft.Data.SqlClient.dll` from the [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.1) package when targeting .NET Framework. See also issue #651 which contains some technical details.

## API Changes
I propose that instead of skipping runtime references altogether on .NET Framework, the `IncludeRuntimeReferences` configuration could default to `false` on .NET Framework and `true`on .NET Core. That would allow the user of Costura to opt-in for embedding runtime references on .NET Framework.

Would you accept a pull request with those changes?

## Intended Use Case
Microsoft.Data.SqlClient could be properly embedded by Costura when targeting .NET Framework this way without needing a [horrible MSBuild trick](https://github.com/Fody/Costura/issues/651#issuecomment-775307190). This would also benefit any other NuGet package that have a `/runtimes` directory with .NET Framework dlls.

### PR DESCRIPTION
**Pull request by 0xced**
### Description of Change ###

With this change, it is possible to embed runtime references under .NET Framework by setting `IncludeRuntimeReferences='true'` in the `FodyWeavers.xml` configuration file for Costura.

### Issues Resolved ### 

- Fixes #652

### API Changes ###
 
None

### Platforms Affected ### 

All

### Behavioral Changes ###

* None from version 4.1.0
* From 5.0.0-beta0001, it's now possible to embed runtime references for .NET Framework

### Testing Procedure ###

This is currently untested, hence the **draft** pull request.

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Review by GeertvanHorrik — APPROVED** [review]

**Comment by GeertvanHorrik** [comment]
I think we can directly merge this into the release branch so we can release another beta.

**Comment by 0xced** [comment]
Wait a sec.

**Comment by 0xced** [comment]
I just force pushed an even simpler version of this pull request. Since including runtime references is opt-in through the `IncludeRuntimeAssemblies` configuration switch anyway, I don't see the need to differentiate the default value of `IncludeRuntimeReferences` between .NET Core and .NET Framework as I did in the previous version of this pull request. Now it always defaults to `true`, no matter the platform.

**Comment by 0xced** [comment]
I just changed the base branch from `develop` to `release/5.0.0`, you can merge it as is.

**Comment by 0xced** [comment]
Thanks for merging, Geert!

**Pull request merged**
