### PR TITLE
Updates Fody & FodyCecil to Latest

### PR DESCRIPTION
**Pull request by CDAGaming**
Updates Dependencies to Latest Versions for Future Nuget Update :)

### CODE REVIEW

**Comment by distantcam** [comment]
Could you also update https://github.com/Fody/Costura/blob/master/src/BuildNuGetPackage/Assets/Costura.Fody.nuspec as well? Thanks

**Comment by CDAGaming** [comment]
Ah Okay :)

**Comment by CDAGaming** [comment]
On Phone so I'll update version from phone hehe

**Comment by CDAGaming** [comment]
All Good to Go Now :)
Or at least it should be

**Pull request merged**
